name: fingerprint_auth_plugin
description: A Flutter plugin for easy biometric authentication (fingerprint and face recognition) on Android and iOS devices. Provides simple methods to check biometric availability and authenticate users securely.
version: 0.1.1 # <<< IMPORTANT : Changez la version à 0.1.1 (ou 0.1.2 si vous avez déjà essayé 0.1.1)
homepage: https://github.com/suzuki233788gfjf/flutter_fingerprint_auth_plugin

environment:
  sdk: '>=3.0.0 <4.0.0' # <<< J'ai mis une contrainte plus large pour le SDK Dart, comme recommandé pour les plugins
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # <<< J'ai mis à jour vers la version 6.0.0, car elle est disponible et améliore le score de linter.

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.fingerprint_auth_plugin # <<< Assurez-vous que c'est bien votre package Android
        pluginClass: FingerprintAuthPlugin
      ios:
        pluginClass: FingerprintAuthPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
